### ISSUE TITLE
Mobile device bug (Android)

### ISSUE THREAD

**Issue by Artsem77** [HichemTab-tech/OTP-designer-jquery#9]
Delete btn don't work when pressed again (test on Android).
Paste code don't work (test on Android).

**Comment by HichemTab-tech** [comment]
Hello,

I wanted to inform you that the issues with the delete button and paste functionality have been successfully resolved. After implementing the necessary changes and pushing the code, both features are now functioning correctly on Android devices. 🎉

Thank you for reporting these issues and helping to improve the repository. If you encounter any other issues or have additional feedback, please don't hesitate to reach out. 😊

Best regards,
@HichemTab-tech
